apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::361672157131:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-O14FG35ALQOY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::361672157131:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T12:43:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3430"
  uid: 29a7234c-1e76-4b24-8e55-14481302cd89
